version: "3.9"

services:
  backend:
    build:
      context: .
    container_name: mailme-backend
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-4000}
      - DOMAIN=${DOMAIN:-mailme.itssvk.dev}
      - FRONTEND_URL=${FRONTEND_URL:-https://mailme.itssvk.dev}
    expose:
      - "${PORT:-4000}"
    volumes:
      - db-data:/app/prisma
    networks:
      - mailme-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: mailme-nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - mailme-network
    restart: unless-stopped

networks:
  mailme-network:
    driver: bridge

volumes:
  db-data:
    driver: local
