version: "3.9"

services:
  backend:
    build:
      context: ./mailme-backend
    container_name: mailme-backend
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-4000}
      - SMTP_PORT=${SMTP_PORT:-2525}
      - DOMAIN=${DOMAIN:-mailme.itssvk.dev}
      - FRONTEND_URL=${FRONTEND_URL:-https://mailme.itssvk.dev}
    expose:
      - "${PORT:-4000}"
      - "${SMTP_PORT:-2525}"
    ports:
      - "${SMTP_PORT:-2525}:${SMTP_PORT:-2525}"
    volumes:
      - db-data:/app/prisma
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: mailme-nginx
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: mailme-certbot
    depends_on:
      - nginx
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    restart: "no"
    entrypoint: >
      sh -c "certbot certonly --webroot
        --webroot-path=/var/www/certbot
        --email admin@itssvk.dev
        --domains mailmeapi.itssvk.dev
        --agree-tos
        --non-interactive"

  certbot-renew:
    image: certbot/certbot
    container_name: mailme-certbot-renew
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c
    command: "trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/certbot && nginx -s reload || true; sleep 12h & wait $${!}; done"
    restart: unless-stopped

volumes:
  db-data:
    driver: local
